version: '3'
services:
  mysql-db:
    image: mysql:latest
    container_name: devops-db
    ports:
      - "3333:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devops_project_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - my-network
    restart: always

  back-app:
    image: hsinemt/devopsproject:backapp
    container_name: spring-back-project
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devops-db:3306/devops_project_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    networks:
      - my-network
    volumes:
      - ./backend-data:/app/data
    restart: always

networks:
  my-network: