services:
  mysql:
    image: mysql:8.0  
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: EyaAbaab-4TWIN1-G1-kaddem
    depends_on:
      - mysql
    ports:
      - "8089:8089"

volumes:
  mysql_data:
