# Server configuration
server.servlet.context-path=/kaddem
server.port=8089

# DATABASE CONFIGURATION (connect to devops-db container)
spring.datasource.url=jdbc:mysql://devops-db:3306/devops_project_db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# Prometheus / Micrometer
management.endpoints.web.exposure.include=prometheus, metrics, info, health, shutdown, beans
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.metrics.export.prometheus.enabled=true
management.security.enabled=false

# Additional Management Properties
management.info.env.enabled=true